[package]
name = "rollup_block_root"
type = "bin"
authors = [""]
compiler_version = ">=0.18.0"

[dependencies]
bigint = { tag = "v0.7.1", git = "https://github.com/noir-lang/noir-bignum" }
sha256 = { tag = "v0.1.3", git = "https://github.com/noir-lang/sha256" }
poseidon = { tag = "v0.1.0", git = "https://github.com/noir-lang/poseidon" }
bigcurve = { tag = "mw/bump", git = "https://github.com/noir-lang/noir_bigcurve" }
