name: Publish Nightly release
on:
  workflow_dispatch:
  schedule:
    # Run a nightly release at 2 AM UTC
    - cron: "0 2 * * *"

jobs:
  public-nargo:
    name: Publish Nargo binary
    uses: ./.github/workflows/publish-nargo.yml
    with:
      # Omitting a tag results in a nightly 
      publish: true

  public-js-packages:
    name: Publish JS packages
    uses: ./.github/workflows/publish-es-packages.yml
    with:
      noir-ref: ${{ env.GITHUB_REF }}
      npm-tag: nightly
