name: Publish Nightly release
on:
  workflow_dispatch:
  schedule:
    # Run a nightly release at 2 AM UTC
    - cron: "0 2 * * *"

jobs:
  dispatch-publish-es:
    runs-on: ubuntu-22.04
    steps:
      - name: Dispatch to publish-nargo
        uses: ./.github/workflows/publish-nargo.yml
        with:
          # Omitting a tag results in a nightly 
          publish: true

      - name: Dispatch to publish-es-packages
        uses: ./.github/workflows/publish-es-packages.yml
        with:
          noir-ref: ${{ env.GITHUB_REF }}
          npm-tag: nightly